### PR TITLE
Fix fixed point parsing

### LINKED ISSUE #63: Negative Fixed-point numbers are probably not working
There are no unit tests for that, and we got an error of an invalid location while submitting attestations, most likely due to bad parsing of negative lattitudes

### PR DESCRIPTION
**Pull request by pifragile**
After a lot of pain I found a one-liner😂
* Closes #63

### CODE REVIEW

File: packages/util/src/parserFixPoint.ts [hunk 1]
```diff
@@ -25,21 +25,24 @@ export interface ParserFixPointFactory {
...
-    const upperBits: string = bits.slice(0, -lower);
-    const decimalPart: number = upperBits ? parseInt(upperBits, 2) : 0;
-    return decimalPart + (raw.isNeg() ? -floatPart : floatPart);
-  };
-}
+    const len = assertLength(upper, lower);
+    return (raw: BN, precision: number = lower): number => {
+        assert(raw.bitLength() <= len, "Bit length is not equal to " + len);
+
+        raw = raw.fromTwos(len);
```
Comment (clangenb) [inline packages/util/src/parserFixPoint.ts:32]: I guess this is the crucial line? It is a bit hard to see because of the mismatch in the indentation depths. But I accept in this case because the original indentation depth, is not the standard, and has been introduced by the creator of this repo. I did not know that we still have some leftovers from this time.

**Review by clangenb — APPROVED** [review]
I fixed the integration tests, if they pass, I think we are good. :)
