### PR TITLE
Fix return correctly show when meetup participant is unassigned

### LINKED ISSUE #43: getMeetupParticipants does not work reliably
This test reproduces the phenomenon from encointer/encointer-wallet-flutter/issues/374

The same account is returned multiple times.

### PR DESCRIPTION
**Pull request by clangenb**
Closes #43 

* Follow-up task #49

### CODE REVIEW

File: packages/util/src/assignment.ts [hunk 1]
```diff
@@ -14,16 +20,63 @@ import assert from "assert";
...
-    // `api.registry` created at `Api` construction.
-    return participantIndex.registry.createTypeUnsafe('ParticipantIndexType', [result]);
+    const meetupIndexFn =
+        (pIndex: ParticipantIndexType, params: AssignmentParams) => meetupIndex(pIndex, params, meetupCount);
+
+    if (!pIndexes[0].eq(0)) {
+        let pIndex = pIndexes[0].subn(1) as ParticipantIndexType;
+        if (pIndex < assignmentCount.bootstrappers) {
+            return meetupIndexFn(pIndex, assignments.bootstrappersReputables)
+        }
```
Comment (clangenb) [inline packages/util/src/assignment.ts:61]: Contrary to my initial diagnosis, the error was in the missing `if` statements.

File: packages/util/src/assignment.ts [hunk 2]
```diff
@@ -34,9 +87,10 @@ export function assignmentFn(participantIndex: ParticipantIndexType, assignmentP
  * @param meetupCount
  */
 export function meetupIndex(participantIndex: ParticipantIndexType, assignmentParams: AssignmentParams, meetupCount: MeetupIndexType): MeetupIndexType {
-    const result = assignmentFn(participantIndex, assignmentParams, meetupCount).add(new BN(1));
 
-    return participantIndex.registry.createTypeUnsafe('MeetupIndexType', [result]);
+    const result = assignmentFn(participantIndex, assignmentParams, meetupCount);
+
+    return result.addn(1) as MeetupIndexType;
 }
```
Comment (clangenb) [inline packages/util/src/assignment.ts:94]: Quite practical; After `addn` the value is a `BN`, but as it has still the `registry` attached to it, we can simply type-cast it back to `MeetupIndexType` instead of having to call `createType`.

**Review by brenzi — APPROVED** [review]
